# H2 DATABASE
spring:
  datasource:
    url: jdbc:h2:mem:basegraphqldb
    driver-class-name: org.h2.Driver
    username: admin
    password: ""
  h2:
    console:
      enabled: true  # URL -> http://localhost:8080/h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  # GraphQL
  graphql:
    graphiql:
      enabled: true
      endpoint: /graphql
      mapping: /graphiql   # URL -> http://localhost:8080/graphiql