-- TB_CATEGORIA
INSERT INTO TB_CATEGORIA (NOME, SITUACAO) VALUES ('Categoria 1', 'ATIVO');

-- TB_PROFESSOR
INSERT INTO TB_PROFESSOR (NOME, BIOGRAFIA, SITUACAO) VALUES ('Professor 1', 'Biografia do Professor 1', 'ATIVO');